Market/Market/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('login/',auth_views.LoginView.as_view(template_name= 'core/login.html'),name = 'login'),
    path('item/', include('item.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Market/core/urls.py
from pipes import Template
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import loginform
from dashboard.views import dashb


urlpatterns = [
    path('', views.home, name = 'home'),
    path('signup/', views.signup, name = 'signup'),
    #path('login/',auth_views.LoginView.as_view(template_name= 'core/login.html'),name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(template_name= 'core/home.html'),name='logout'),
    path('dash/', dashb, name='dash'),
    ]

Market/item/urls.py
from django.urls import path, include
from .views import detail, additem, delitem, edititem, browse


app_name = 'item'

urlpatterns = [
    path('<int:pk>/detail', detail, name = 'detail'),
    path('additem/', additem, name = 'add-item'),
    path('<int:pk>/delete', delitem, name = 'del-item'),
    path('<int:pk>/edit', edititem, name = 'edit-item'),
    path('browse/', browse, name = 'browse'),
    path('<int:pk>/', detail, name = 'detail'),
    
    ]

Market/dashboard/models.py
from django.db import models

# Create your models here.

Market/item/models.py
from tabnanny import verbose
from django.db import models
from django.contrib.auth.models import User



class category(models.Model):

    name = models.CharField(max_length=20)

    class Meta:
        
        ordering = ('name',)
        verbose_name_plural = ('Catergories')

    def __str__(self):
        return self.name



class item(models.Model):

    name = models.CharField(max_length=50)
    description = models.TextField(blank = True,null = True)
    price = models.IntegerField()
    categ = models.ForeignKey(category, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='item_images/',blank = True, null = True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    sold = models.BooleanField(default=False)

    class Meta:
        
        ordering = ('name',)
        

    def __str__(self):
        return self.name

Market/core/forms.py


from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from item.models import item


class register(UserCreationForm):

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

        username = forms.CharField(widget = forms.TextInput(attrs ={ 'placeholder':'username'}))
        email = forms.EmailField(widget = forms.PasswordInput(attrs ={ 'placeholder':'email'}))
        password1 = forms.CharField(widget = forms.PasswordInput(attrs ={ 'placeholder':'password'}))
        password2 = forms.CharField(widget = forms.PasswordInput(attrs ={ 'placeholder':'re-enter password'}))
        
class loginform(AuthenticationForm):
    
    class Meta:
        model = User
        fields = ('username','password1')

        username = forms.CharField(widget = forms.TextInput(attrs ={ 'placeholder':'username'}))
        password1 = forms.CharField(widget = forms.PasswordInput(attrs ={ 'placeholder':'password'}))


Market/item/forms.py
from django import forms
from .models import item, category


class add(forms.ModelForm):

     class Meta:
        
        model = item
        fields = ('categ','name','price','description','img')

        categ = forms.CharField(widget = forms.TextInput(attrs ={ 'placeholder':'category'}))
        name = forms.CharField(widget = forms.TextInput(attrs ={ 'placeholder':'name'}))
        description = forms.Textarea(attrs ={ 'placeholder':'name'})
        price = forms.CharField(widget = forms.TextInput(attrs ={ 'placeholder':'price'}))
        


class edit(forms.ModelForm):
    
    
    class Meta:

        model = item
        fields = ('name','price','description','img','sold')

Market/core/views.py

from django.shortcuts import render, redirect
from item.models import item, category
from .forms import register


def home(request):

    context = {
        'items': item.objects.filter(sold=False)[0:6],
        'category': category.objects.all,
        }
    return render(request,'core/home.html',context)


def signup(request):
    if request.method == 'POST':
        form = register(request.POST)

        if form.is_valid():
            form.save()
            return redirect('login')
        
    else:
        form = register()

    return render(request, 'core/signup.html', {'form':form})

    


Market/dashboard/views.py

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from item.models import item



@login_required
def dashb(request):

    
    items = item.objects.filter(created_by=request.user)
        
    return render(request, 'dashboard/dash.html',{'items':items})



Market/item/views.py

from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import item, category
from .forms import add, edit
from django.db.models import Q


def detail(request, pk):
    
    context = {
        'item': get_object_or_404(item,pk=pk),
        #'related_items': item.objects.filter(categ = item.categ, sold = False).exclude(pk=pk)[0:6]
        }
    return render(request,'item/detail.html',context)


@login_required
def additem(request):
    if request.method == 'POST':
        form = add(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
          
            return redirect('item:detail', pk=item.id)
    form = add()
    return render(request, 'item/additem.html', {'form':form})


@login_required
def delitem(request, pk):
    context = {
        'item': get_object_or_404(item,pk=pk, created_by=request.user)
        }
    context['item'].delete()
    return render(request,'dashboard/dash.html')


@login_required
def edititem(request, pk):

    Item = get_object_or_404(item,pk=pk, created_by=request.user)
    if request.method == 'POST':
        form = edit(request.POST, request.FILES,instance= Item)

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=Item.id)
    form = edit(instance= Item)
    return render(request, 'item/edititem.html', {'form':form})


def browse(request):
    category_id = request.GET.get('category',0)
    context = {
    'items': item.objects.filter(sold=False),
    'query': request.GET.get('query',''),
    'category_id':request.GET.get('category',0),
    'category': category.objects.all,
        }
    if category_id:
        category_id = context['items'].filter(categ_id=category_id)
    if context['query']:
        context['items'] = context['items'].filter(Q(name__icontains=context['query']) | Q(description__icontains=context['query']))
    category_id = int(category_id)
    context['category_id']=category_id 
    return render(request,'item/browse.html',context)

Market/core/templates/core/base.html


<!DOCTYPE html>
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
    <link href="{% static 'core/StyleSheet1.css' %}" rel="stylesheet" />
</head>


<body>
    <div class="nav">
        
        <div class="nav-item">

            <a href="{% url 'home' %}">Home</a>
            <a href="{% url 'item:browse' %}">Browse</a>
            <a href="{% url 'dash'%}">Dashboard</a>

        </div>

        <div class="nav-item">

            {%if user.is_authenticated%}

            <button onclick="location.href = {% url 'logout' %}">LogOut</button>

            {%else%}

            <button onclick="location.href={% url 'login' %} ">LogIn</button>
            <button onclick="location.href={% url 'signup' %} ">Register</button>
            {%endif%}

        </div>
        
    </div>

    {%block content%}{%endblock%}
</body>
</html>

Market/core/templates/core/home.html
{%extends 'core/base.html'%}


{%block content%}
<div class="container">
    {%for item in items%}
    <div class="item-cont">


        <a href="{%url 'item:detail' item.id%}"><img src="{{item.img.url}}" alt="{{item.name}}" /></a>

        <div class="item-txt">
            <h3>{{item.name.title}}</h3>
            <p>{{item.price}}$</p>
        </div>

    </div>
    {%endfor%}

</div>

<hr />

<div class="categ">
    
        
    {%for categ in category%}
       <a href="#">{{categ.name.capitalize}}</a>

    {%endfor%}
        
    
</div>

        

    


{%endblock%}

Market/core/templates/core/login.html
{%extends 'core/base.html'%}
{% load crispy_forms_tags %}

{%block content%}


<div class="form">
    <h1>LogIn</h1>
    <form method="POST">
        {%csrf_token%}
        {{form|crispy}}
        <button onclick="location.href =?next = {%url 'home' %}" type="submit">LogIn</button>
    </form>
</div>



{%endblock%}

Market/core/templates/core/signup.html
{%extends 'core/base.html'%}
{% load crispy_forms_tags %}

{%block content%}
<div class="form signup">
    <h1>SignUp</h1>

    <form method="POST">
        {%csrf_token%}
        {{form |crispy}}
        <button type="submit">SignUp</button>
    </form>


</div>


{%endblock%}

Market/dashboard/templates/dashboard/dash.html
{%extends 'core/base.html'%}



{%block content%}


<div class="add-item" >
    <a href="{%url 'item:add-item'%}">Add Item</a>
</div>




<div class="container">
    {%for item in items%}
    <div class="item-cont">


        <a href="{%url 'item:detail' item.id%}"><img src="{{item.img.url}}" alt="{{item.name}}" /></a>

        <div class="item-txt">
            <h3>{{item.name}}</h3>
            <p>{{item.price}}$</p>
        </div>


    </div>

    {%endfor%}
    

</div>
<div>
    <div>
        {%for categ in category%}

        <a href="#">{{categ.name}}</a>

        {%endfor%}
    </div>
</div>


{%endblock%}

Market/item/templates/item/additem.html
{%extends 'core/base.html'%}
{% load crispy_forms_tags %}

{%block content%}
<div class="form">

    <form class="add-form" method="POST" enctype="multipart/form-data">
        {%csrf_token%}
        {{form |crispy}}
        <button type="submit">Add</button>
    </form>

</div>



{%endblock%}

Market/item/templates/item/browse.html
{%extends 'core/base.html'%}


{%block content%}
<div class="container">
    {%for item in items%}
    <div class="item-cont">


        <a href="{%url 'item:detail' item.id%}"><img src="{{item.img.url}}" alt="{{item.name}}" /></a>

        <div class="item-txt">
            <h3>{{item.name.title}}</h3>
            <p>{{item.price}}$</p>
        </div>

    </div>
    {%endfor%}

</div>

{%for categ in category%}

<a href="{%url 'item:browse'%}?=query={{query}}&category={{categ.id}}">{{categ.name.title}}</a>

{%endfor%}

<form action="{% url 'item:browse' %}" method="GET">
    <input type="text" name="query" value="{{query}}" />
    <button>Search</button>
</form>
{%endblock%}

Market/item/templates/item/detail.html
{%extends 'core/base.html'%}


{%block content%}

<div class="det-cont">
    
        <img src="{{item.img.url}}" alt="{{item.name}}" />
    
    
    <div class="det-txt">
        <h2 style="line-height:0px;">{{item.name}}</h2>
        <p style="line-height:0px;">{{item.categ}}</pstyle="line-height:0px;">
        <p>by:{{item.created_by}} &nbsp&nbsp {{item.created_at}}</p>
        <p class="price">Price:{{item.price}}$</p>
        <h3>Description:</h3>
        <p>{{item.description}}</p>

        
        {%if request.user == item.created_by%}

        <div class="det-anchor">
            <a href="{%url 'item:edit-item' item.id%}">Edit</a>
            <a style="background-color:red" href="{%url 'item:del-item' item.id%}">Delete</a>
        </div>
        

        {%endif%}

    </div>

</div>


{%endblock%}

Market/item/templates/item/edititem.html
{%extends 'core/base.html'%}
{% load crispy_forms_tags %}


{%block content%}

<div class="form">
    <form class="add-form" method="POST">
        {%csrf_token%}
        {{form|crispy}}
        <button  type="submit">Apply</button>
    </form>
</div>

{%endblock%}